backend:
    menus:


        - name: "课程管理"
          url: "/backend/courses"
          icon: "tachometer-alt"
        - name: "视频管理"
          url: "/backend/videos"
          icon: "tachometer-alt"
        - name: "章节管理"
          url: "/backend/empty"
          icon: "square"
        - name: "评论管理"
          url: "/backend/empty"
          icon: "square"
spring:
  datasource:
    url: jdbc:mysql://47.99.133.120:3306/lms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: soft
    password: soft
    driver-class-name: com.mysql.cj.jdbc.Driver
#
#mybatis-plus:
#  #mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
